### ISSUE TITLE
Solution to Sod shock tube diverges from analytic solution beyond t = 0.3

### ISSUE THREAD

**Issue by rodluger** [rodluger/hydro#1]
I _think_ there's something fishy with the analytic solution, so I'm going to investigate that.

**Comment by rodluger** [comment]
Yeah, I'm pretty sure the Sod problem assumes an _infinitely_ long tube, so the analytic solution does not have any explicit boundary conditions! So let's not worry about what happens beyond t = 0.5. I've added a line to prevent the user from specifying an end time above this value.

**Comment by frelikh** [comment]
Oh that makes sense! Great.
